name: Publish to NPM Registry

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Enable Corepack & setup pnpm v10.20.0
        run: |
          corepack enable
          corepack prepare pnpm@10.20.0 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: pnpm install

      - name: Test project
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Detect tag and bump version in package.json
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_VERSION="${GITHUB_REF##*/}"
            NEW_VERSION="${TAG_VERSION#v}"
            jq --arg version "$NEW_VERSION" '.version = $version' package.json > package.tmp.json
            mv package.tmp.json package.json
          else
            echo "::error::Este workflow sรณ pode ser disparado por uma tag!"
            exit 1
          fi

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
